import { PostItem, StoryItem, GroupItem, UserProfile, ReactionType } from '../types';

export const FB_REACTIONS: { type: ReactionType; label: string; emoji: string; color: string; bg: string }[] = [
  { type: 'like', label: 'Like', emoji: '👍', color: '#1877F2', bg: 'hover:bg-blue-50 text-blue-600' },
  { type: 'love', label: 'Love', emoji: '❤️', color: '#F33E5B', bg: 'hover:bg-red-50 text-red-500' },
  { type: 'care', label: 'Care', emoji: '🥰', color: '#F7B125', bg: 'hover:bg-yellow-50 text-amber-500' },
  { type: 'haha', label: 'Haha', emoji: '😆', color: '#F7B125', bg: 'hover:bg-yellow-50 text-amber-500' },
  { type: 'wow', label: 'Wow', emoji: '😮', color: '#F7B125', bg: 'hover:bg-yellow-50 text-amber-500' },
  { type: 'sad', label: 'Sad', emoji: '😢', color: '#F7B125', bg: 'hover:bg-yellow-50 text-amber-500' },
  { type: 'angry', label: 'Angry', emoji: '😡', color: '#E9710F', bg: 'hover:bg-orange-50 text-orange-600' },
];

export const FEELING_OPTIONS = [
  { emoji: '😊', label: 'Happy' },
  { emoji: '🥰', label: 'Loved' },
  { emoji: '🔥', label: 'Excited' },
  { emoji: '🥳', label: 'Celebrating' },
  { emoji: '😎', label: 'Cool' },
  { emoji: '☕', label: 'Drinking Coffee' },
  { emoji: '🍕', label: 'Eating Pizza' },
  { emoji: '✈️', label: 'Traveling' },
  { emoji: '🎧', label: 'Listening to Music' },
  { emoji: '💪', label: 'Working Out' },
  { emoji: '📚', label: 'Reading' },
  { emoji: '💻', label: 'Coding' },
  { emoji: '😴', label: 'Tired' },
  { emoji: '🎨', label: 'Creative' },
  { emoji: '🏖️', label: 'Relaxing' },
  { emoji: '🎮', label: 'Gaming' },
];

export const POPULAR_LOCATIONS = [
  'Dhaka, Bangladesh',
  'Chittagong, Bangladesh',
  'Sylhet, Bangladesh',
  'Cox\'s Bazar Beach',
  'Gulshan, Dhaka',
  'New York, United States',
  'London, United Kingdom',
  'Paris, France',
  'Tokyo, Japan',
  'Dubai, United Arab Emirates',
  'Singapore',
  'Toronto, Canada',
];

export const POST_GRADIENTS = [
  { id: 'none', label: 'Normal', value: '' },
  { id: 'g1', label: 'Sunset Glow', value: 'bg-gradient-to-tr from-orange-500 via-rose-500 to-amber-400 text-white font-bold text-xl min-h-[220px] flex items-center justify-center text-center p-8' },
  { id: 'g2', label: 'Facebook Blue', value: 'bg-gradient-to-r from-blue-600 via-indigo-600 to-sky-500 text-white font-bold text-xl min-h-[220px] flex items-center justify-center text-center p-8' },
  { id: 'g3', label: 'Neon Emerald', value: 'bg-gradient-to-br from-emerald-600 via-teal-600 to-cyan-500 text-white font-bold text-xl min-h-[220px] flex items-center justify-center text-center p-8' },
  { id: 'g4', label: 'Deep Purple', value: 'bg-gradient-to-tr from-purple-700 via-pink-600 to-rose-400 text-white font-bold text-xl min-h-[220px] flex items-center justify-center text-center p-8' },
  { id: 'g5', label: 'Dark Cyber', value: 'bg-gradient-to-r from-slate-900 via-purple-950 to-slate-900 text-cyan-300 font-bold text-xl min-h-[220px] flex items-center justify-center text-center p-8' },
  { id: 'g6', label: 'Golden Luxury', value: 'bg-gradient-to-tr from-amber-600 via-yellow-500 to-orange-400 text-slate-900 font-bold text-xl min-h-[220px] flex items-center justify-center text-center p-8' },
];

export const SEED_USERS: UserProfile[] = [
  {
    id: 'user_tushar',
    full_name: 'Tushar Mehmed',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    cover_url: 'https://images.unsplash.com/photo-1707343843437-caacff5cfa74?w=1200&auto=format&fit=crop&q=80',
    bio: 'Tech enthusiast & Creator | Building StepBook 🚀',
    work: 'Software Architect at StepBook Inc.',
    education: 'Computer Science & Engineering',
    location: 'Dhaka, Bangladesh',
    relationship: 'Single',
    website: 'https://stepbook.social',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    verified: true,
  },
  {
    id: 'user_sarah',
    full_name: 'Sarah Rahman',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
    cover_url: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=1200&auto=format&fit=crop&q=80',
    bio: 'Photographer 📷 & Coffee Lover ☕ | Exploring life one click at a time ✨',
    work: 'Lead Visual Designer at Creative Studio',
    education: 'Fine Arts & Photography',
    location: 'Chittagong, Bangladesh',
    relationship: 'In a relationship',
    website: 'https://sarahvisuals.com',
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
    verified: true,
  },
  {
    id: 'user_alex',
    full_name: 'Alex Johnson',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    cover_url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1200&auto=format&fit=crop&q=80',
    bio: 'Outdoor adventurer 🏔️ | Tech speaker 🎙️ | React & AI enthusiast',
    work: 'Developer Advocate',
    education: 'MIT Alumni',
    location: 'San Francisco, CA',
    relationship: 'Married',
    created_at: new Date(Date.now() - 200 * 86400000).toISOString(),
    verified: true,
  },
  {
    id: 'user_aisha',
    full_name: 'Aisha Chowdhury',
    avatar_url: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&auto=format&fit=crop&q=80',
    cover_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    bio: 'Passionate foodie 🍲 | Travel blogger 🗺️ | Living my best life!',
    work: 'Food Critic & Content Creator',
    education: 'Culinary Arts & Journalism',
    location: 'Sylhet, Bangladesh',
    relationship: 'Single',
    created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
    verified: false,
  },
  {
    id: 'user_zayan',
    full_name: 'Zayan Khan',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80',
    cover_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    bio: 'Music Producer 🎵 | Synthesizers & beats | Let the rhythm speak 🎧',
    work: 'Sound Engineer at BeatWave',
    education: 'Audio Engineering Academy',
    location: 'Dhaka, Bangladesh',
    created_at: new Date(Date.now() - 150 * 86400000).toISOString(),
    verified: true,
  },
  {
    id: 'user_anika',
    full_name: 'Anika Tabassum',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
    cover_url: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=1200&auto=format&fit=crop&q=80',
    bio: 'Frontend Architect 💻 | Open Source Contributor | Cat mom 🐱',
    work: 'Senior Frontend Engineer',
    education: 'Software Engineering',
    location: 'Rajshahi, Bangladesh',
    created_at: new Date(Date.now() - 80 * 86400000).toISOString(),
    verified: false,
  }
];

export const SEED_STORIES: StoryItem[] = [
  {
    id: 'story_1',
    user_id: 'user_sarah',
    media_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80',
    caption: 'Golden sunset at the coast today 🌅🌊',
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    user: SEED_USERS[1],
  },
  {
    id: 'story_2',
    user_id: 'user_alex',
    media_url: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&auto=format&fit=crop&q=80',
    caption: 'Campfire under the starry mountain skies ⛺✨',
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    user: SEED_USERS[2],
  },
  {
    id: 'story_3',
    user_id: 'user_aisha',
    media_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=80',
    caption: 'Handmade wood-fired pizza! 🍕🔥',
    created_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    user: SEED_USERS[3],
  },
  {
    id: 'story_4',
    user_id: 'user_zayan',
    media_url: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80',
    caption: 'Late night studio sessions with analog gear 🎛️🎹',
    created_at: new Date(Date.now() - 11 * 3600000).toISOString(),
    user: SEED_USERS[4],
  },
  {
    id: 'story_5',
    user_id: 'user_anika',
    media_url: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&auto=format&fit=crop&q=80',
    caption: 'Coffee + Code = Perfect morning flow ☕💻',
    created_at: new Date(Date.now() - 14 * 3600000).toISOString(),
    user: SEED_USERS[5],
  }
];

export const SEED_GROUPS: GroupItem[] = [
  {
    id: 'grp_tech_bd',
    name: 'JavaScript & Web Developers Bangladesh',
    description: 'The largest community of JavaScript, React, Node.js and full-stack developers in Bangladesh.',
    cover_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1000&auto=format&fit=crop&q=80',
    avatar_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=300&auto=format&fit=crop&q=80',
    privacy: 'public',
    created_by: 'user_tushar',
    members_count: 14280,
    is_member: true,
    created_at: new Date(Date.now() - 300 * 86400000).toISOString(),
  },
  {
    id: 'grp_photography',
    name: 'Bangladesh Photography Club',
    description: 'Share your best captures, portrait tips, street photography, and landscape moments!',
    cover_url: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=1000&auto=format&fit=crop&q=80',
    avatar_url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=300&auto=format&fit=crop&q=80',
    privacy: 'public',
    created_by: 'user_sarah',
    members_count: 38900,
    is_member: true,
    created_at: new Date(Date.now() - 400 * 86400000).toISOString(),
  },
  {
    id: 'grp_travelers',
    name: 'Travelers of Bangladesh & Beyond',
    description: 'Guide, itineraries, stories, and hotel reviews for backpackers and travelers.',
    cover_url: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1000&auto=format&fit=crop&q=80',
    avatar_url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=300&auto=format&fit=crop&q=80',
    privacy: 'public',
    created_by: 'user_aisha',
    members_count: 92450,
    is_member: false,
    created_at: new Date(Date.now() - 500 * 86400000).toISOString(),
  },
  {
    id: 'grp_startups',
    name: 'Tech Startups & Founders Hub',
    description: 'Connecting innovators, angel investors, growth hackers, and startup founders.',
    cover_url: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=1000&auto=format&fit=crop&q=80',
    avatar_url: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=300&auto=format&fit=crop&q=80',
    privacy: 'public',
    created_by: 'user_alex',
    members_count: 8520,
    is_member: false,
    created_at: new Date(Date.now() - 250 * 86400000).toISOString(),
  }
];

export const SEED_POSTS: PostItem[] = [
  {
    id: 'post_1',
    user_id: 'user_sarah',
    content: 'Welcome to StepBook! 🚀 Just captured this scenic sunset during our evening walk along the seashore. The colors in the sky were utterly mesmerizing. What do you all think? 🌊📸 #SunsetVibes #Photography #StepBook',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&auto=format&fit=crop&q=80',
    feeling: { emoji: '🥰', label: 'Blessed' },
    location: 'Cox\'s Bazar Beach',
    privacy: 'public',
    created_at: new Date(Date.now() - 35 * 60000).toISOString(),
    user: SEED_USERS[1],
    shares_count: 14,
    reactions: [
      { id: 'r1', post_id: 'post_1', user_id: 'user_tushar', reaction_type: 'love' },
      { id: 'r2', post_id: 'post_1', user_id: 'user_alex', reaction_type: 'like' },
      { id: 'r3', post_id: 'post_1', user_id: 'user_aisha', reaction_type: 'wow' },
      { id: 'r4', post_id: 'post_1', user_id: 'user_zayan', reaction_type: 'love' },
      { id: 'r5', post_id: 'post_1', user_id: 'user_anika', reaction_type: 'care' },
    ],
    user_reaction: 'love',
    comments: [
      {
        id: 'c1',
        post_id: 'post_1',
        user_id: 'user_tushar',
        content: 'Absolutely breathtaking capture Sarah! The composition and lighting are top notch 🔥',
        created_at: new Date(Date.now() - 25 * 60000).toISOString(),
        user: SEED_USERS[0],
        likes_count: 3,
        user_liked: true,
      },
      {
        id: 'c2',
        post_id: 'post_1',
        user_id: 'user_aisha',
        content: 'I was there last weekend too! Such a peaceful spot ❤️',
        created_at: new Date(Date.now() - 15 * 60000).toISOString(),
        user: SEED_USERS[3],
        likes_count: 1,
      }
    ]
  },
  {
    id: 'post_2',
    user_id: 'user_alex',
    content: '🎉 Big milestone reached today: We just released our open-source framework update with full TypeScript 5.8 support and sub-millisecond edge rendering! Huge thanks to everyone testing and giving feedback! 🚀💻',
    feeling: { emoji: '🔥', label: 'Excited' },
    location: 'San Francisco, CA',
    privacy: 'public',
    bg_gradient: 'bg-gradient-to-r from-blue-600 via-indigo-600 to-sky-500 text-white font-bold text-xl min-h-[220px] flex items-center justify-center text-center p-8',
    created_at: new Date(Date.now() - 120 * 60000).toISOString(),
    user: SEED_USERS[2],
    shares_count: 28,
    reactions: [
      { id: 'r6', post_id: 'post_2', user_id: 'user_tushar', reaction_type: 'like' },
      { id: 'r7', post_id: 'post_2', user_id: 'user_anika', reaction_type: 'haha' },
      { id: 'r8', post_id: 'post_2', user_id: 'user_zayan', reaction_type: 'wow' },
    ],
    user_reaction: 'like',
    comments: [
      {
        id: 'c3',
        post_id: 'post_2',
        user_id: 'user_anika',
        content: 'Congrats Alex! Can’t wait to integrate this into our upcoming pipeline ⚡',
        created_at: new Date(Date.now() - 90 * 60000).toISOString(),
        user: SEED_USERS[5],
        likes_count: 2,
      }
    ]
  },
  {
    id: 'post_3',
    user_id: 'user_aisha',
    content: 'Sunday brunch with homemade pasta and traditional berry tart 🍝🍰 If anyone wants the secret sauce recipe let me know in the comments below!',
    image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80',
    feeling: { emoji: '🍕', label: 'Eating Pizza' },
    location: 'Gulshan, Dhaka',
    privacy: 'public',
    created_at: new Date(Date.now() - 360 * 60000).toISOString(),
    user: SEED_USERS[3],
    shares_count: 5,
    reactions: [
      { id: 'r9', post_id: 'post_3', user_id: 'user_sarah', reaction_type: 'love' },
      { id: 'r10', post_id: 'post_3', user_id: 'user_tushar', reaction_type: 'care' },
    ],
    comments: [
      {
        id: 'c4',
        post_id: 'post_3',
        user_id: 'user_sarah',
        content: 'Please send me the recipe ASAP! Looks so delicious 😋',
        created_at: new Date(Date.now() - 300 * 60000).toISOString(),
        user: SEED_USERS[1],
        likes_count: 4,
      }
    ]
  }
];
